function ctd_select()

% CTD_SELECT:  CSIRO CTD cast selection menu - main program.
%
% For HELP, see  /home/eez_data/pub_web/doc/ctd_select.html   which is
% web-viewable as http://www.marine.csiro.au/eez_data/doc/ctd_select.html
%
%  Copyright     Jeff Dunn, CSIRO Division of Marine Research, 29/1/1998

% $Id: ctd_select.m,v 1.2 2000/10/20 03:58:34 dunn Exp $
% Matlab version 5.0
% This code manually modified after creation using Matlab5 GUIDE


disp(' Reading station list and constructing menu ....')

load ctd_select

a = figure('Units','points', ...
	'Color',[0.7 0.7 0.7], ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'PaperType','a4letter', ...
	'Position',[0 150 563.52 362.88], ...
	'Tag','Fig1');

% --------- Static text

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',14, ...
	'FontWeight','demi', ...
	'ForegroundColor',[0 0 1], ...
	'Position',[10 329 300 23.04], ...
	'String','CSIRO  CTD  data  selection  menu', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',14, ...
	'FontWeight','demi', ...
	'ForegroundColor',[0 1 1], ...
	'Position',[360 329 190 23], ...
	'String','                       ', ...
	'Tag','update', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Position',[383.04 307.2 57.6 16.32], ...
	'String','Year', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Position',[321.6 309.12 57.6 14.4], ...
	'String','Month', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Position',[269.76 307.2 57.6 15.36], ...
	'String','Day', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Position',[315 209.28 194.88 19.2], ...
	'String','Min number of t & s values per cast:', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',12, ...
	'Position',[16.32 257.28 62.4 20.16], ...
	'String','REGION', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',12, ...
	'Position',[172.8 245.76 12.48 21.12], ...
	'String','N', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',12, ...
	'Position',[176.64 185.28 12.48 21.12], ...
	'String','S', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',12, ...
	'Position',[14.4 215.04 23.04 21.12], ...
	'String','W', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'FontSize',12, ...
	'Position',[216.96 216.96 17.28 21.12], ...
	'String','E', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Position',[234.24 256.32 48 15.36], ...
	'String','MAX  >', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Position',[236.16 288 48 15.36], ...
	'String','MIN  >', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Position',[173.76 92.16 48 15.36], ...
	'String','MAX  >', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Position',[173.76 128.64 48 15.36], ...
	'String','MIN  >', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Position',[217.92 146.88 60.48 13.44], ...
	'String','Cruise', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Position',[304.32 146.88 60.48 13.44], ...
	'String','Station', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Position',[381.12 145.92 89.28 13.44], ...
	'String','Bottom Depth', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Position',[481.92 146.88 60.48 13.44], ...
	'String','Data Depth', ...
	'Style','text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.3 0.3 0.4], ...
	'Position',[8.64 68 545.28 6.72], ...
	'Style','text');

    
% ------- Range selection controls

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','ctd_sel_util(''reset_lims'')', ...
	'FontSize',12, ...
	'Position',[30 300 110. 25.], ...
	'String','Reset all limits');

    %	'Position',[84.48 288.96 110. 25.],
    
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','ctd_sel_util(''franklin'')', ...
	'Position',[21 155 81 19.2], ...
	'String','Frankin', ...
	'Style','checkbox', ...
	'Tag','franklin');
b = uicontrol('parent',a, ...
	'Units','points', ...
	'Callback','ctd_sel_util(''surveyor'')', ...
	'Position',[21 135 81 19.2], ...
	'String','Surveyor', ...
	'Style','checkbox', ...
	'Tag','surveyor');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','ctd_sel_util(''aurora'')', ...
	'Position',[21 115 81 19.2], ...
	'String','Aurora', ...
	'Style','checkbox', ...
	'Tag','aurora');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','ctd_sel_util(''sprightly'')', ...
	'Position',[21 95 81 19.2], ...
	'String','Sprightly', ...
	'Style','checkbox', ...
	'Tag','sprightly');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','ctd_sel_util(''soela'')', ...
	'Position',[21 75 81 19.2], ...
	'String','Soela', ...
	'Style','checkbox', ...
	'Tag','soela');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''w_region'')', ...
	'Position',[37.44 218.88 80.64 22.08], ...
	'Style','edit', ...
	'Tag','w_region');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''e_region'')', ...
	'Position',[134.4 219.84 80.64 22.08], ...
	'Style','edit', ...
	'Tag','e_region');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''n_region'')', ...
	'Position',[90.24 251.52 80.64 22.08], ...
	'Style','edit', ...
	'Tag','n_region');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''s_region'')', ...
	'Position',[88.32 190.08 80.64 22.08], ...
	'Style','edit', ...
	'Tag','s_region');

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','ctd_sel_util(''eachyr'')', ...
	'Position',[447 258 115 42], ...
	'String','',...
	'Style','checkbox', ...
	'Tag','eachyr');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','', ...
	'Position',[465 265 80 28], ...
	'String',{'Same day/month','in each year'}, ...
	'Style','text');

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''yearmin'')', ...
	'Position',[384 287 48.96 20.16], ...
	'Style','edit', ...
	'Tag','yearmin');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''yearmax'')', ...
	'Position',[384 253 48.96 20.16], ...
	'Style','edit', ...
	'Tag','yearmax');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''monmin'')', ...
	'Position',[334 287 29.76 21.12], ...
	'Style','edit', ...
	'Tag','monmin');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''monmax'')', ...
	'Position',[334 253 29.76 21.12], ...
	'Style','edit', ...
	'Tag','monmax');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''daymin'')', ...
	'Position',[281 287 29.76 21.12], ...
	'Style','edit', ...
	'Tag','daymin');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''daymax'')', ...
	'Position',[281 253 29.76 21.12], ...
	'Style','edit', ...
	'Tag','daymax');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''crmax'')', ...
	'Position',[220.8 90.24 48.96 20.16], ...
	'Style','edit', ...
	'Tag','crmax');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''crmin'')', ...
	'Position',[220.8 126.72 48.96 20.16], ...
	'Style','edit', ...
	'Tag','crmin');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''ddepmin'')', ...
	'Position',[489.6 125.76 48.96 20.16], ...
	'Style','edit', ...
	'Tag','ddepmin');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''ddepmax'')', ...
	'Position',[490.56 89.28 48.96 20.16], ...
	'Style','edit', ...
	'Tag','ddepmax');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''bdepmin'')', ...
	'Position',[402.24 126.72 48.96 20.16], ...
	'Style','edit', ...
	'Tag','bdepmin');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''bdepmax'')', ...
	'Position',[402.24 89.28 48.96 20.16], ...
	'Style','edit', ...
	'Tag','bdepmax');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''stmin'')', ...
	'Position',[310.08 126.72 48.96 20.16], ...
	'Style','edit', ...
	'Tag','stmin');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''stmax'')', ...
	'Position',[310.08 90.24 48.96 20.16], ...
	'Style','edit', ...
	'Tag','stmax');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ctd_sel_util(''sampmin'')', ...
	'Position',[500 210 40 21.12], ...
	'Style','edit', ...
	'Tag','sampmin');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','ctd_sel_util(''needdig'')', ...
	'Position',[340 175 170.0 19.2], ...
	'String','Require CTD digistiser', ...
	'Style','checkbox', ...
	'Tag','needdig');

    
% ------- Activity controls

b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','ctd_sel_util(''finish'')', ...
	'FontSize',12, ...
	'Position',[391.68 7.68 144 20.16], ...
	'String','Finish', ...
	'Tag','finish');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','ctd_sel_util(''clear_all'')', ...
	'FontSize',12, ...
	'Position',[391.68 37.44 144 20.16], ...
	'String','Clear all selected', ...
	'Tag','clear_all');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','ctd_sel_util(''save_to_file'')', ...
	'FontSize',12, ...
	'Position',[198.72 6.72 144 20.16], ...
	'String','Write to File', ...
	'Tag','save_to_file');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','ctd_sel_util(''save_sel'')', ...
	'FontSize',12, ...
	'Position',[200.64 38.4 144 20.16], ...
	'String','Store selection', ...
	'Tag','save_sel');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','ctd_sel_util(''test_sel'')', ...
	'FontSize',12, ...
	'Position',[17.28 38.4 144 20.16], ...
	'String','Test selection', ...
	'Tag','test_sel');


ctd_sel_util('reset_lims');

    
% ----------------------------------------------------------------
