% VAL2:  Sub-menu for cast selection for validate.m
%
%  Copyright     Jeff Dunn, CSIRO Marine Research March 2003
% 
% USAGE:  not user callable - invoked only by "validate" GUI

function val2

global ncf alert Vdeph Vlevh guih

guih{2} = figure('Units','points', ...
      'Color',[0.7 0.7 0.7], ...
      'MenuBar','none', ...
      'PaperType','a4letter', ...
      'Name','Cast Selection', ... 
      'NumberTitle','off', ...
      'Position',[200 100 130 140]);

% Cast selection controls

b = uicontrol('Parent',guih{2}, ...
      'Units','points', ...
      'BackgroundColor',[0.7 0.7 0.7], ...
      'Style','text', ...
      'FontSize',12, 'Fontweight','demi', ...
      'Position',[5 120 120 20], ...
      'String','Cast Selection');
b = uicontrol('Parent',guih{2}, ...
      'Units','points', ...
      'BackgroundColor',[0.7 0.7 0.7], ...
      'Style','text', ...
      'FontSize',10, ...
      'Position',[5 100 120 20], ...
      'Tag','num_casts', ...
      'String','Number of casts: 0');
b = uicontrol('Parent',guih{2}, 'Units','points', ...
      'BackgroundColor',[0.7 0.7 0.7], ...
      'Callback','val_util(''next_cast'')', ...
      'FontSize',10, ...
      'Position',[10 80 110 20], ...
      'String','Next cast');
b = uicontrol('Parent',guih{2}, ...
      'Units','points', ...
      'BackgroundColor',[0.7 0.7 0.7], ...
      'Style','text', ...
      'FontSize',10, ...
      'Position',[10 50 60 20], ...
      'String','Cast num:');
b = uicontrol('Parent',guih{2}, ...
      'Units','points', ...
      'BackgroundColor',[1 1 1], ...
      'Callback','val_util(''num_cast'')', ...
      'Style','edit', ...
      'FontSize',10, ...
      'Position',[90 55 30 20], ...
      'Tag','castnum', ...
      'String','');
b = uicontrol('Parent',guih{2}, 'Units','points', ...
      'BackgroundColor',[0.7 0.7 0.7], ...
      'Callback','val_util(''sel_cast'')', ...
      'FontSize',10, ...
      'Position',[10 30 110 20], ...
      'String','Select on map');



b = uicontrol('Parent',guih{2}, 'Units','points', ...
      'Callback','val_util(''finish2'')', ...
      'FontSize',12, ...
      'Position',[80 5 50 20], ...
      'String','Close');


val_util('init2')

%---------------------------------------------------------------------------
