% VAL4:  Sub-menu for difference map plot, in Validate program 
%
%  Copyright     Jeff Dunn, CSIRO Marine Research March 2003
% 
% USAGE:  not user callable - invoked only by "validate" GUI

function val4

global ncf alert guih Vdeph Vlevh

guih{4} = figure('Units','points', ...
      'Color',[0.7 0.7 0.7], ...
      'MenuBar','none', ...
      'PaperType','a4letter', ...
      'Name','Diff map config', ... 
      'NumberTitle','off', ...
      'Position',[0 40 200 170]);

b = uicontrol('Parent',guih{4}, ...
      'Units','points', ...
      'FontSize',12, ...
      'Style','text', ...
      'Position',[5 150 190 15], ...
      'String','Difference map configuration');

b = uicontrol('Parent',guih{4}, ...
      'Units','points', ...
      'ForegroundColor',[.2 0 .8], ...
      'Style','text', ...
      'HorizontalAlignment','right', ...
      'Position',[5 130 125 15], ...
      'String','Range is +/- A, where A =');
b = uicontrol('Parent',guih{4}, ...
      'Units','points', ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',[.2 0 .8], ...
      'Callback','val_util(''set_rng'')', ...
      'FontSize',10, ...
      'Position',[130 130 40 20], ...
      'String','', ...
      'Tag','4_rng', ...
      'Style','edit');
b = uicontrol('Parent',guih{4}, ...
      'Units','points', ...
      'ForegroundColor',[.2 0 .8], ...
      'Style','text', ...
      'HorizontalAlignment','center', ...
      'Position',[5 112 190 15], ...
      'String','Clear field to active autoscaling');

depcol = [0.8 0.2 0];
b = uicontrol('Parent',guih{4}, ...
      'Units','points', ...
      'FontSize',12, ...
      'ForegroundColor',depcol, ...
      'Position',[10 83 180 15], ...
      'String','Depth level of map', ...
      'Style','text');
b = uicontrol('Parent',guih{4}, ...
      'Units','points', ...
      'ForegroundColor',depcol, ...
      'Position',[30 50 60 30], ...
      'String','Depth', ...
      'Style','text', ...
      'Tag','4_depth');
b = uicontrol('Parent',guih{4}, ...
      'Units','points', ...
      'ForegroundColor',depcol, ...
      'Position',[110 50 60 30], ...
      'String','Level', ...
      'Style','text', ...
      'Tag','4_level');

Vdeph(3) = uicontrol('Parent',guih{4}, ...
      'Units','points', ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',depcol, ...
      'Callback','val_util(''d_dep'')', ...
      'FontSize',10, ...
      'Position',[30 34 60 20], ...
      'String','', ...
      'Style','edit');
Vlevh(3) = uicontrol('Parent',guih{4}, ...
      'Units','points', ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',depcol, ...
      'Callback','val_util(''d_lev'')', ...
      'FontSize',10, ...
      'Position',[110 34 60 20], ...
      'String','', ...
      'Style','edit');

b = uicontrol('Parent',guih{4}, ...
      'Units','points', ...
      'Callback','val_util(''finish4'')', ...
      'FontSize',10, ...
      'Position',[155 5 40 20], ...
      'String','Close');


val_util('init4')

%---------------------------------------------------------------------------
