% VAL5:  Sub-menu for scatter plot, in Validate program 
%
%  Copyright     Jeff Dunn, CSIRO Marine Research March 2003
% 
% USAGE:  not user callable - invoked only by "validate" GUI

function val5

global ncf alert guih Vdeph Vlevh guih

guih{5} = figure('Units','points', ...
      'Color',[0.7 0.7 0.7], ...
      'MenuBar','none', ...
      'PaperType','a4letter', ...
      'Name','Scatter plot config', ... 
      'NumberTitle','off', ...
      'Position',[0 40 240 130]);

b = uicontrol('Parent',guih{5}, ...
      'Units','points', ...
      'FontSize',12, ...
      'Style','text', ...
      'Position',[15 110 190 15], ...
      'String','Scatter plot configuration');

depcol = [0.8 0.2 0];
b = uicontrol('Parent',guih{5}, ...
      'Units','points', ...
      'FontSize',12, ...
      'ForegroundColor',depcol, ...
      'Position',[10 83 220 15], ...
      'String','Single depth or range eg 33 3', ...
      'Style','text');
b = uicontrol('Parent',guih{5}, ...
      'Units','points', ...
      'ForegroundColor',depcol, ...
      'Position',[20 50 80 30], ...
      'String','Depth', ...
      'Style','text', ...
      'Tag','5_depth');
b = uicontrol('Parent',guih{5}, ...
      'Units','points', ...
      'ForegroundColor',depcol, ...
      'Position',[120 50 80 30], ...
      'String','Level', ...
      'Style','text', ...
      'Tag','5_level');

Vdeph(2) = uicontrol('Parent',guih{5}, ...
      'Units','points', ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',depcol, ...
      'Callback','val_util(''5_dep'')', ...
      'FontSize',10, ...
      'Position',[20 34 80 20], ...
      'String','', ...
      'Style','edit');
Vlevh(2) = uicontrol('Parent',guih{5}, ...
      'Units','points', ...
      'BackgroundColor',[1 1 1], ...
      'ForegroundColor',depcol, ...
      'Callback','val_util(''5_lev'')', ...
      'FontSize',10, ...
      'Position',[120 34 80 20], ...
      'String','', ...
      'Style','edit');

b = uicontrol('Parent',guih{5}, ...
      'Units','points', ...
      'Callback','val_util(''finish5'')', ...
      'FontSize',10, ...
      'Position',[190 5 40 20], ...
      'String','Close');


val_util('init5')

%---------------------------------------------------------------------------
